# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

# This makes Click behave itself.
env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

docker_builder:
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - Lint
    - Zipapp_bootstrap
    - Linux
    - macOS
    - FreeBSD
    #- Windows
    - repos
  env:
    DOCKER_USERNAME: ENCRYPTED[a957943032559f0859a16a4421bc3602338080e6d9ce63a980db4fd34dbdc2afbe3a20c620139c669182eced4211a515]
    DOCKER_PASSWORD: ENCRYPTED[dd7f31d490b645298258ac9ec78ac3a7e034e8bfcf8fbfec0137787eef3934e01a42ef3b5eda42b1b1f7a3296fae619e]
  build_script:
    - docker build --tag duckinator/bork:${CIRRUS_TAG} --tag duckinator/bork:latest --build-arg "VERSION=${CIRRUS_TAG}" .
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push duckinator/bork:$CIRRUS_TAG duckinator/bork:latest

Lint_task:
  container:
    image: python:3-slim
  install_script:
    - pip install .
    - pip install .[testing]
  script:
    - flake8 --version
    - pylint --version
    - bork run lint

Zipapp_bootstrap_task:
  container:
    matrix:
      image: python:3.7-slim
      image: python:3.8-slim
  setup_script:
    - cp -r . /tmp/bork-pristine
    - cp -r /tmp/bork-pristine /tmp/pass1
    - cp -r /tmp/bork-pristine /tmp/pass2
    - cp -r /tmp/bork-pristine /tmp/pass3
  # Make sure Bork can build itself.
  pass_1_script:
    - cd /tmp/pass1
    - python3 --version
    - pip install . .[testing]
    - bork build
  # Make sure the Bork zipapp from Pass 1 can build Bork.
  pass_2_script:
    - cd /tmp/pass2
    - cp /tmp/pass1/dist/bork-*.pyz /tmp/bork-pass1.pyz
    - python3 /tmp/bork-pass1.pyz build
  # Make sure the Bork zipapp built from Pass 2 can build Bork.
  # ime with other self-building software, this is prone to blowing up.
  pass_3_script:
    - cd /tmp/pass3
    - cp /tmp/pass2/dist/bork-*.pyz /tmp/bork-pass2.pyz
    - python3 /tmp/bork-pass2.pyz build
    - cp ./dist/bork-*.pyz /tmp/bork-pass3.pyz
    - python3 /tmp/bork-pass3.pyz run lint

Linux_task:
  container:
    matrix:
      - image: python:3.6-slim
      - image: python:3.7-slim
      - image: python:3.8-slim
  install_script:
    - pip install . .[testing]
  script:
    - python3 --version
    - bork run test

macOS_task:
  osx_instance:
    image: catalina-xcode
  env:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    PATH: ${HOME}/.pyenv/shims:${PATH}
    matrix:
      - PYTHON: 3.6.8
      - PYTHON: 3.7.2
  install_script:
    # Per the pyenv homebrew recommendations.
    # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    - brew install openssl readline pyenv
    - pyenv install ${PYTHON}
    - pyenv global ${PYTHON}
    - pyenv rehash
    - pip install -e .[testing]
  script:
    - python3 --version
    - bork run test

FreeBSD_task:
  freebsd_instance:
    image_family: freebsd-12-1-snap
  env:
    matrix:
      - PYTHON: 3.6
      - PYTHON: 3.7
  install_script:
    - PY=`echo $PYTHON | tr -d '.'`
    - pkg install -y python${PY} py${PY}-setuptools
    - python${PYTHON} -m ensurepip
    - python${PYTHON} -m pip install -e .[testing]
  script:
    - python${PYTHON} --version
    - bork run test

# Windows_task:
#   allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
#   windows_container:
#     os_version: 2019
#     matrix:
#       - image: python:3.6-windowsservercore-1809
#       - image: python:3.7-windowsservercore-1809
#       - image: python:3.8-rc-windowsservercore-1809

#   install_script:
#     - C:\Python\python.exe -m pip install -e .[testing]
#   script:
#     - C:\Python\python.exe --version
#     - C:\Python\python.exe -m pytest --verbose

repos_task:
  container:
    image: python:3-slim
  env:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
    matrix:
      - REPO: https://github.com/ppb/ppb-vector.git
      - REPO: https://github.com/duckinator/emanate.git
      - REPO: https://github.com/duckinator/bork.git
      - REPO: https://github.com/astronouth7303/ppb-mutant.git
  install_script:
    - apt-get update
    - apt-get install -y git
    - pip3 install .
  script:
    - git clone $REPO /tmp/repo
    - cd /tmp/repo
    - bork clean
    - bork build
    - bork release --dry-run

release_task:
  only_if: "changesInclude('bork/__init__.py')"
  trigger_type: manual
  depends_on:
    - Lint
    - Zipapp_bootstrap
    - Linux
    - macOS
    - FreeBSD
    #- Windows
    - repos
  container:
    image: python:3.8-slim
  install_script:
    - pip3 install . .[testing]
  build_script:
    - bork clean
    - bork build
  test_script:
    - bork run test
  #release_script:
  #  - bork release
