status = [
  "FreeBSD PYTHON:3.6",
  "FreeBSD PYTHON:3.7",
  "Lint",
  "Linux container:python:3.6-slim",
  "Linux container:python:3.7-slim",
  "Linux container:python:3.8-slim",
  "Zipapp_bootstrap container:python:3.7-slim",
  "Zipapp_bootstrap container:python:3.8-slim",
  "macOS PYTHON:3.6.8",
  "macOS PYTHON:3.7.2",
]

delete_merged_branches = true
