[build-system]
# Specify the required build system.
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.bork.zipapp]
# bork can not build a functional zipapp of itself yet.
enabled = false
main = "bork.cli:main"

[tool.bork.aliases]
lint = "pylint bork"
test = "pytest --pylint --flake8 --verbose"
